### ISSUE TITLE
On the training of gan networks

### ISSUE THREAD

**Issue by ZackSoul** [mnswdhw/InvGAN-Pytorch#1]
Is there any training code about your defensegan network and Invgan network? I want to observe the specific training process

**Comment by mnswdhw** [comment]
Did you check these files, https://github.com/mnswdhw/InvGAN-Pytorch/blob/main/defense_gan.py and https://github.com/mnswdhw/InvGAN-Pytorch/blob/main/invgan.py 
These files have the training codes as well. Please note that I am using pre-trained weights of these GANs provided here https://github.com/yogeshbalaji/InvGAN These are in TensorFlow, so you will have to load them appropriately into PyTorch models.
