### ISSUE TITLE
 About Conversion Scripts

### ISSUE THREAD

**Issue by ZackSoul** [mnswdhw/InvGAN-Pytorch#2]
![image](https://user-images.githubusercontent.com/91828262/211508615-85068afa-17bf-412c-9af0-b94d017e9727.png)
In your conversion script, as shown in the figure, I found that there seem to be two functions missing, Do you have the code for these two functions? I am also reproducing this paper recently. Thank you very much.

**Comment by mnswdhw** [comment]
I have taken some code from the original author of this paper, InvGAN. You can find the relevant code here https://github.com/yogeshbalaji/InvGAN/blob/master/utils/config.py Let me know if there is any other issue with the code.
